name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore  --configuration Release

      - name: Debug Environment Variables
        run: |
          # Don't actually print the secret values, just verify they are not empty
          if [ -z "${{ secrets.TWILIOOPTIONS__ACCOUNTSID }}" ]; then echo "AccountSid is empty"; fi
          if [ -z "${{ secrets.TWILIOOPTIONS__AUTHTOKEN }}" ]; then echo "AuthToken is empty"; fi
          if [ -z "${{ secrets.TWILIOOPTIONS__PHONENUMBER }}" ]; then echo "PhoneNumber is empty"; fi

      - name: Test
        env:
          Twilio_TwilioOptions__AccountSid: ${{ secrets.TWILIOOPTIONS__ACCOUNTSID }}
          Twilio_TwilioOptions__AuthToken: ${{ secrets.TWILIOOPTIONS__AUTHTOKEN }}
          Twilio_TwilioOptions__PhoneNumber: ${{ secrets.TWILIOOPTIONS__PHONENUMBER }}
        run: dotnet test --no-restore --verbosity normal
